# use container-based infrastructure
sudo: false
#sudo: required
#dist: trusty
env:
  - USE_TRAVIS=true

language: python

python:
  - "2.7"

#virtualenv:
#  system_site_packages: true

before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq cython python-matplotlib python-numexpr python-numpy python-yaml python-sip python-scipy
#  - sudo apt-get install -qq cython python-yaml python-sip
#  - sudo apt-get build-dep python-tables
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,tables,cython numpy scipy tables numexpr matplotlib cython pyyaml
  - pip install flake8  # Not yet available in Debian stable

install:
  - pip install -e .
  - python setup.py build_ext --inplace

script:
  - make test-ci
